name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download Cloud SQL Auth Proxy
        run: wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy && chmod +x cloud_sql_proxy

      - name: Run Cloud SQL Auth Proxy
        run: ./cloud_sql_proxy -instances="your-project-id:region:instance-id"=tcp:3306 &
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1.1.0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: encoded-yen-440913-i1

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1.1.0
        with:
          project_id: encoded-yen-440913-i1

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run Prisma Migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx prisma migrate deploy

      - name: Check Prisma Migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: echo "DATABASE_URL is set"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure Docker to use gcloud as a credential helper
        run: gcloud auth configure-docker asia-southeast2-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t asia-southeast2-docker.pkg.dev/encoded-yen-440913-i1/my-repo/githubactiondeploy:latest .

      - name: Push Docker image to Artifact Registry
        run: |
          docker push asia-southeast2-docker.pkg.dev/encoded-yen-440913-i1/my-repo/githubactiondeploy:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy githubactiondeploy \
            --image asia-southeast2-docker.pkg.dev/encoded-yen-440913-i1/my-repo/githubActionDeploy:latest \
            --platform managed \
            --region asia-southeast2 \
            --project encoded-yen-440913-i1 \
            --allow-unauthenticated
            --no-source